services:
  api:
    build: .
    image: nxp-digit-inference:latest
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
